<?php

namespace DoctrineORMModule\Proxy\__CG__\Catalog\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Money extends \Catalog\Entity\Money implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'id', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'name', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyGroup', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyUnit', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moreInfo', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyMoving', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyStock', 'sm'];
        }

        return ['__isInitialized__', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'id', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'name', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyGroup', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyUnit', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moreInfo', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyMoving', '' . "\0" . 'Catalog\\Entity\\Money' . "\0" . 'moneyStock', 'sm'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Money $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyGroup', []);

        return parent::getMoneyGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyGroup($moneyGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyGroup', [$moneyGroup]);

        return parent::setMoneyGroup($moneyGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyUnit', []);

        return parent::getMoneyUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyUnit($moneyUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyUnit', [$moneyUnit]);

        return parent::setMoneyUnit($moneyUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoreInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoreInfo', []);

        return parent::getMoreInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoreInfo($moreInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoreInfo', [$moreInfo]);

        return parent::setMoreInfo($moreInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyMoving()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyMoving', []);

        return parent::getMoneyMoving();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyMoving($moneyMoving)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyMoving', [$moneyMoving]);

        return parent::setMoneyMoving($moneyMoving);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyStock', []);

        return parent::getMoneyStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyStock($moneyStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyStock', [$moneyStock]);

        return parent::setMoneyStock($moneyStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceManager(\Interop\Container\ContainerInterface $sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceManager', [$sm]);

        return parent::setServiceManager($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceManager', []);

        return parent::getServiceManager();
    }

}
