<?php
/**
 * Created by PhpStorm.
 * User: stellar
 * Date: 2016.10.21.
 * Time: 4:01
 */

$orderTable = $this->datatable();
$haveOrderedTable = clone $this->datatable();
?>

<h1><?= $this->translate('Rendelés') ?></h1>
<h2><?= $fromName ?> <span class="glyphicon glyphicon-arrow-right"> </span> <?= $toName ?></h2>


<?php echo $orderTable->renderFromModel($datatableModel) ?>

<h2><?= $this->translate('Eddig rendelt termékek'); ?></h2>
<?php echo $haveOrderedTable->renderFromModel($datatableListing) ?>


<div id="ingr-transaction-fieldset">
    <?php echo $this->formCollection($form->get('StockTransaction')); ?>
</div>


<script>
    //kitöröljük az alapértelmezett 1 a valuból, majd ha kattint, akkor kell
    $('.extrainputhidden').each(function () {
        $(this).val('');
    });

    $("form#order-form").append($("#ingr-transaction-fieldset"));

    $('.modal-body').append($('[for="ingr-transaction-more-info"]'));
    $('.modal-body').append($('#ingr-transaction-more-info'));
    $('[for="ingr-transaction-more-info"]').attr('style', 'font-weight:normal');


</script>




