<?php
/**
 * Created by PhpStorm.
 * User: stellar
 * Date: 2016.10.30.
 * Time: 9:53
 */
?>

<h1><?= $this->translate('Beállítások'); ?></h1>

<div class="row">
    <div class="col-lg-6">
        <table class="table menulist">
            <tbody>
            <tr>
                <td><span class="glyphicon glyphicon-user"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('user'); ?>">
                        <?= $this->translate('Felhasználók'); ?></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>