<?php
/**
 * Created by PhpStorm.
 * User: stellar
 * Date: 2016.11.02.
 * Time: 9:05
 */
?>


<h1><?= $this->translate("Lekérdezés"); ?></h1>


<div class="row">
    <div class="col-lg-6">
        <table class="table menulist">
            <tbody>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="destination-list biglist"
                       href="<?= $this->url('stocktransactionhistory', ['action' => 'income']) ?>">
                        <?= $this->translate('Napi bevételek'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="destination-list biglist"
                       href="<?= $this->url('stocktransactionhistory', ['action' => 'stocktransactionchoose']) ?>">
                        <?= $this->translate('Készletműveletek'); ?></a>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</div>
