<?php
/**
 * Created by PhpStorm.
 * User: stellar
 * Date: 2016.10.19.
 * Time: 1:23
 */
?>

<h1><?= $this->translate('Eszköz készletek'); ?></h1>

<?= $this->datatable()->renderFromModel($datatableModel) ?>

<h1><?= $this->translate('Készletműveletek') ?></h1>

<div class="row">
    <div class="col-lg-6">
        <table class="table menulist">
            <tbody>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('tooltransactionchoose', ['action' => 'toolreceive']) ?>">
                        <?= $this->translate('Eszköz bevételezés'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('tooltransactionchoose', ['action' => 'toolreturn']) ?>">
                        <?= $this->translate('Eszköz visszárú'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('tooltransactionchoose', ['action' => 'toolmove']) ?>">
                        <?= $this->translate('Eszköz átvételezés'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('tooltransactionchoose', ['action' => 'toolstockcorrection']) ?>">
                        <?= $this->translate('Eszköz készletkorrekció (leltár)'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('tooltransactionchoose', ['action' => 'tooldiscard']) ?>">
                        <?= $this->translate('Eszköz selejtezés'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('tooltransactionchoose', ['action' => 'tooluniversal']) ?>">
                        <?= $this->translate('Univerzális eszköz-mozgatás'); ?></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
