<?php
/**
 * Created by PhpStorm.
 * User: stellar
 * Date: 2016.10.25.
 * Time: 8:14
 */
?>


<h1><?= $this->translate("Rendelési helyek"); ?></h1>


<div class="row">
    <div class="col-lg-6">
        <table class="table menulist">
            <tbody>
            <?php foreach ($destinations as $destination): ?>

                <tr>
                    <td><span class="glyphicon glyphicon-chevron-right"></span>
                        <a class="destination-list biglist"
                           href="<?= $this->url('producttransaction', ['action' => 'destination', 'from' => $destination->getId()]) ?>">
                            <?= $destination->getName(); ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

