<?php
/**
 * Created by PhpStorm.
 * User: stellar
 * Date: 2016.10.19.
 * Time: 1:23
 */
?>

<h1><?= $this->translate('Alapanyag készletek'); ?></h1>

<?= $this->datatable()->renderFromModel($datatableModel) ?>

<h1><?= $this->translate('Készletműveletek') ?></h1>

<div class="row">
    <div class="col-lg-6">
        <table class="table menulist">
            <tbody>

            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'receive']) ?>">
                        <?= $this->translate('Alapanyag bevételezés'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'return']) ?>">
                        <?= $this->translate('Alapanyag visszárú'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'move']) ?>">
                        <?= $this->translate('Alapanyag átvételezés'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'stockcorrection']) ?>">
                        <?= $this->translate('Alapanyag készletkorrekció (leltár)'); ?></a>
                </td>
            </tr>
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'discard']) ?>">
                        <?= $this->translate('Alapanyag selejtezés'); ?></a>
                </td>
            </tr>
            <!-- TODO: #143  <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'discardproduct']) ?>">
                        <?= $this->translate('Termék selejtezés'); ?></a>
                </td>
            </tr>-->
            <tr>
                <td><span class="glyphicon glyphicon-chevron-right"></span>
                    <a class="basedata-list"
                       href="<?= $this->url('ingrtransactionchoose', ['action' => 'universal']) ?>">
                        <?= $this->translate('Univerzális alapanyag-mozgatás'); ?></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>